### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BoGuu** [AsYetUntitled/Framework#1]
- [x] Tanoa
- [x] Finish the extDB3 predefined statements build (sql_custom).
- [x] Fix the admin markers (not removing old markers), and prevent multiple loops being spawned. (https://github.com/AsYetUntitled/Framework/pull/66)
- [ ] Add custom jail times.
- [ ] Add percentage mining to tempest device.
- [x] Fix device issue (see https://github.com/ArmaLife/Framework/issues/802)
- [x] Add level/license checks to relevant configs.
  - [x] Weapon
  - [x] vItems
- [ ] Allow a custom price to be set for any vehicle in a shop (override multipliers) [https://github.com/AsYetUntitled/Framework/pull/124] 
- [ ] Move over action menus to unified configs, and utilize a listbox. Item pick up can be added to this.
- [ ] Make some use for playtime - y menu, admin menu, etc. Or remove it.
- [ ] Remove all uses of BIS_fnc_param, and use params (as much as possible) and param in other situations.
- [ ] Updated gang system - levels etc
- [x] Housing Config
  - [x] Tanoa
  - [X] Altis
- [x] Wanted System Cleanup
- [ ] Move over to private _keywords_ where possible for clarity
- [ ] Player tags config

Possibly (perhaps a separate build)
- [ ] Optional database based phone.
- [ ] Create a new optional phone GUI

**Comment by Heavybob** [comment]
*thumbs up*

**Comment by fresqo** [comment]
ill look at admin markers tonight

**Comment by fresqo** [comment]
i have gang levels on my server, a temporary invite ability and gang xp. it also shows offline members and has a cap of 10 players. What system do you want and i can look at this also..

**Comment by Heavybob** [comment]
Oi, the reason multiplers were put in was to prevent people from having to write 4 different things into the veh config. 
Buy Price
Sell Price
Rent Price
Insurance Price.

Multipliers work buy using once defined number for each car and then calculating the other bits of data. This is very relevant as if multipliers are removed then it will then again be easy for people to fuck the prices of veh by making the sell price higher than the buy price or rent price too much to buy. It saves everyone the time and effort. Also allows people to adjust the economy for each server quickly without too much hassle.

**Comment by trinitynet** [comment]
Multipliers NEED to go. i understand they are easier but if people are fucking up changing a simple number then they should not be doing it -.-

**Comment by fresqo** [comment]
I thought multipliers were easier? are they a major issue?. In regards to chop shop, i think a variable set on vehicle if its (civ,cop,med,reb) would be good so when chopped it can grab the proper bought price instead of just using the civ price, which could be abused since there could be major differences between civ price to cop price of a vehicle. thus making ransoming vehicles relevant

**Comment by Heavybob** [comment]
IT ALREADY DOES THAT

**Comment by fresqo** [comment]
oh, sry.. must just be my old version

**Comment by trinitynet** [comment]
lol, chill on the caps rofl

**Comment by Heavybob** [comment]
If you completely remove muliplyers, you will be adding 3 new lines to each veh.

**Comment by trinitynet** [comment]
not got a prob with that

**Comment by fresqo** [comment]
actually just looking at the master, there is just one multiplier for chopping. which would mean its irrelevant of if its a cop.civ.med.reb priced vehicle.. i think it would work better if it was relevant to the side price imo

**Comment by Heavybob** [comment]
Its not irelivent if you have cars which are cheaper for cops than civs as many servers do. Cops die more than civs and inturn things are cheaper.

**Comment by Heavybob** [comment]
Find a actual proof link that multipliers are worse than set pricing.  @BoGuu listed once example to me that if you had two car shops with the same car and one price for that car being different than the other intentionally wanting people to visit different areas to buy cheap cars then it would be a problem.

**Comment by trinitynet** [comment]
on your server maybe, the point is being able to define all prices manually makes things alot easier. trust me i'm fed up with having to calculate the differences and so is everyone else.

**Comment by Heavybob** [comment]
This is an issue with you not understanding how fractions work. Not an issue with the code.

**Comment by BoGuu** [comment]
Heil BoGuu

**Comment by trinitynet** [comment]
http://prntscr.com/bviu76 and %'s dont do that?

**Comment by Heavybob** [comment]
no it doesn't

**Comment by Heavybob** [comment]
taking argument to discord
https://discord.gg/6vmBZ

**Comment by trinitynet** [comment]
#triggered

**Comment by Heavybob** [comment]
DO NOT REMOVE PLAY TIME!
