### ISSUE TITLE
Tanoa TODO

### ISSUE THREAD

**Issue by BoGuu** [AsYetUntitled/Framework#6]
- [ ] Finish garage system (variable check for blacklisted houses)
  - [] Variable check for blacklisted houses
  - [ ] Add option to buy garage to house menu
- [ ] Recreate hospital objects, as to not break a lot of the medic functionality.
